import React, { useState, useEffect } from 'react';
import { AlertTriangle, X } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export default function DisclaimerModal({ isAr }: { isAr: boolean }) {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    const hasSeenDisclaimer = localStorage.getItem('osint_disclaimer_seen');
    if (!hasSeenDisclaimer) {
      setIsOpen(true);
    }
  }, []);

  const handleClose = () => {
    localStorage.setItem('osint_disclaimer_seen', 'true');
    setIsOpen(false);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="bg-[#111111] border border-[#27272a] rounded-lg shadow-2xl max-w-md w-full overflow-hidden relative"
            dir={isAr ? 'rtl' : 'ltr'}
          >
            <div className="p-4 border-b border-[#27272a] bg-[#161618] flex items-center justify-between">
              <div className="flex items-center gap-2 text-[#fbbf24]">
                <AlertTriangle className="w-5 h-5" />
                <span className="font-bold tracking-wider text-sm">EXPERIMENTAL RELEASE V0.01</span>
              </div>
              <button onClick={handleClose} className="text-[#a1a1aa] hover:text-white transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="p-6 space-y-4 text-sm text-[#d4d4d8] leading-relaxed">
              <p>
                <strong>Notice:</strong> This application is currently in an experimental phase and remains incomplete. We assume absolutely no responsibility or liability for any reports, analyses, or intelligence generated by this tool.
              </p>
              <p>
                <strong>TREND ENGINE</strong> is an experimental OSINT dashboard designed to analyze digital trends, uncover how they were artificially or organically manufactured, and track "trend crimes" to discover the real issues hidden behind viral movements.
              </p>
              <p className="text-xs text-[#a1a1aa] italic border-t border-[#27272a] pt-4 mt-4">
                By continuing to use this application, you acknowledge that this is a prototype tool in active development.
              </p>
            </div>

            <div className="p-4 bg-[#161618] border-t border-[#27272a] flex justify-end">
              <button 
                onClick={handleClose}
                className="bg-[#fbbf24] hover:bg-[#d97706] text-black font-bold uppercase tracking-wider text-xs px-6 py-2.5 rounded transition-colors"
              >
                I Acknowledge
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
